### ISSUE TITLE
How to input Image into defish-ppm?

### ISSUE THREAD

**Issue by dicksonchin** [bovine/defish#1]
Don't know how to load images into the source code

**Comment by bovine** [comment]
It takes no command-line arguments, and reads the image from from stdin. As with NetPBM-style utilities, you will likely need to combine other utilities to convert to/from the ppm format or do any additional image processing steps that you require.


    jpegtopnm capture.jpg | defish-ppm | pnmtojpeg defish.jpg

**Comment by dicksonchin** [comment]
By stdin you mean keyboard? that means after running defish-ppm in Ubuntu, type
"jpegtopnm capture.jpg | defish-ppm | pnmtojpeg defish.jpg "?

**Comment by bovine** [comment]
No, my command listed above would be the command-line at the unix shell prompt for running it. You will need the NetPBM utilities also installed.
